- name: Run the Solution
  hosts: localhost
  tasks:
    - name: Tear down existing services
      community.docker.docker_compose:
        project_src: php-application-with-haproxy-and-nginx
        state: absent
    - name: Run docker compose to create containers
      community.docker.docker_compose:
        project_name: php-application-with-haproxy-and-nginx
        definition:
          services:
            php-app:
              build: ./php-application
              ports:
                - "1000:80"
              links:
                - nginx
            nginx:
              image: nginx
              ports:
                - "8080:8080"
              volumes:
                - "./nginx/nginx.conf:/etc/nginx/nginx.conf:ro"
              links:
                - "haproxy"
            haproxy:
              image: haproxy
              ports: 
                - "80:80"
              volumes:
                - "./haproxy:/usr/local/etc/haproxy:ro"
      register: output


    